### ISSUE TITLE
Make `CLIENT_SECRET` visible after the client enters their password 

### ISSUE THREAD

**Issue by algomaster99** [IMGIITRoorkee/omniport-frontend-developer#2]
`CLIENT_SECRET` is a very sensitive information and must be protected at all costs. The reason being, if compromised, the attacker can make their own app and use it to steal data from the service providing `OAuth` if the client's app is approved. A nice feature would be to hide the `CLIENT_SECRET` and require the client (or all other team members) to enter their password to view it.

**Comment by gauransh7** [comment]
I would like to work on this issue.

**Comment by algomaster99** [comment]
@gauransh7 go for it :100:
